In [1]:
!pip install numpy

In [3]:
import numpy as np

In [7]:
# Random Numbers
data = np.random.randn(2, 3, 4)

# Zeroes
zeroes = np.zeros((2, 2, 2))

# Ones
ones = np.ones((2, 2, 2))

# Array full of the number '7'
full = np.full((2, 2, 2), 7)

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [10]:
# Shape of Array
print("Shape: ", shape)

# Size of Array (Length)
print("Size: ", size)

# Types of Array
print("Types: ", types)

Shape:  (2, 3, 4)
Size:  24
Types:  float64


In [12]:
# Slicing
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
single_val = data[0][0][0]

print("Array: ", arr)
print("\nSlicer: ", slicer)
print("\nReverse: ", reverse)
print("\nSingle Value: ", single_val)

Array:  [[-1.59447856  0.4398296  -0.52026061  1.45759518]
 [ 1.09718817 -0.19316821 -2.07384365 -0.55342014]
 [ 1.77657487 -1.16677323  0.74333947 -0.84605345]]

Slicer:  [[[-1.59447856  0.4398296  -0.52026061  1.45759518]
  [ 1.09718817 -0.19316821 -2.07384365 -0.55342014]
  [ 1.77657487 -1.16677323  0.74333947 -0.84605345]]

 [[ 0.74582017 -0.19164065  1.67459287  0.21038183]
  [ 1.36169248  1.80893616 -0.1241268  -0.16462048]
  [ 0.62797233  0.34520336  1.26923251  0.29546932]]]

Reverse:  [[ 0.74582017 -0.19164065  1.67459287  0.21038183]
 [ 1.36169248  1.80893616 -0.1241268  -0.16462048]
 [ 0.62797233  0.34520336  1.26923251  0.29546932]]

Single Value:  -1.5944785553520529


In [14]:
list1 = np.random.randn(10)
list2 = np.random.randn(10)

# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mul = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [15]:
print("Add: ", add)
print("\nSub: ", sub)
print("\nDiv: ", div)
print("\nMul: ", mul)
print("\nDot: ", dot)

Add:  [-0.16558812  1.34944793 -0.76948134  0.01190055 -0.86124773  2.50196024
 -1.54505148  1.92872604  0.62742049 -1.14698088]

Sub:  [ 2.26031226 -0.29953235 -1.16144575  1.45801848  0.96693635  0.88619718
 -1.23891458  1.88019369  0.76914979  0.37760844]

Div:  [-8.63483168e-01  6.36705967e-01 -4.92628169e+00 -1.01645861e+00
 -5.78107071e-02  2.09693951e+00  9.09385995e+00  7.84820792e+01
 -9.85378661e+00  5.04642418e-01]

Mul:  [-1.27039802  0.43282252 -0.18921367 -0.53141907 -0.04830456  1.36861491
  0.21306868  0.04621396 -0.04948373  0.29324425]

Dot:  0.2651452681149501


In [17]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
exp = np.exp([2, 5])
max = np.max(list1)
min = np.min(list1)

# Print
print("Sqrt: ", sqrt)
print("\nAbs: ", ab)
print("\nPower: ", power)
print("\nLog: ", log)
print("\nExp: ", exp)
print("\nMax: ", max)
print("\nMin: ", min)

Sqrt:  5.0

Abs:  2

Power:  256

Log:  3.2188758248682006

Exp:  [  7.3890561 148.4131591]

Max:  1.9044598675272455

Min:  -1.3919830318045712


In [19]:
# Change Values
data[0][0][0] = 1000
data

array([[[ 1.00000000e+03,  4.39829596e-01, -5.20260605e-01,
          1.45759518e+00],
        [ 1.09718817e+00, -1.93168212e-01, -2.07384365e+00,
         -5.53420138e-01],
        [ 1.77657487e+00, -1.16677323e+00,  7.43339470e-01,
         -8.46053450e-01]],

       [[ 7.45820171e-01, -1.91640653e-01,  1.67459287e+00,
          2.10381827e-01],
        [ 1.36169248e+00,  1.80893616e+00, -1.24126796e-01,
         -1.64620482e-01],
        [ 6.27972327e-01,  3.45203357e-01,  1.26923251e+00,
          2.95469316e-01]]])

In [20]:
data.sort()
data

array([[[-5.20260605e-01,  4.39829596e-01,  1.45759518e+00,
          1.00000000e+03],
        [-2.07384365e+00, -5.53420138e-01, -1.93168212e-01,
          1.09718817e+00],
        [-1.16677323e+00, -8.46053450e-01,  7.43339470e-01,
          1.77657487e+00]],

       [[-1.91640653e-01,  2.10381827e-01,  7.45820171e-01,
          1.67459287e+00],
        [-1.64620482e-01, -1.24126796e-01,  1.36169248e+00,
          1.80893616e+00],
        [ 2.95469316e-01,  3.45203357e-01,  6.27972327e-01,
          1.26923251e+00]]])

In [21]:
data.shape

(2, 3, 4)

In [22]:
data = data.reshape(2, 6, -1)

In [24]:
data.shape

(2, 6, 2)